export { cacheCtx, flushCache } from './queries/cache.js';
export {
  pacientesActivosConPropietario,
  consultasEnSeguimiento,
  historialPaciente,
  propietariosConMultiplesPacientes,
  veterinariosActivosConConsultas60d,
  pacientesConVacunasVencidas,
  topDiagnosticos,
  stockBajo,
  controlesBaratos,
  pacientesPorSucursal,
  ingresosPorVetMesActual,
  propietariosSinConsultasUltimoAnio,
  altaPropietario,
  modificarPropietario,
  bajaPropietario,
  altaConsulta,
  decrementarStock,
} from './queries/index.js';
